"""
_audit_wave_2.py — Story 2.7 Wave-2 audit.

Pure-stdlib Python. For each wave-2 tool, runs scripts/rubric-lint.py to
mechanically score it against docs/quality-rubric.md, captures the per-
criterion table, and APPENDS a Wave-2 section to docs/quality-audit.md
(preserving any Wave-1 section above it byte-for-byte).

Usage:
    python scripts/_audit_wave_2.py           # audit + append to docs/quality-audit.md
    python scripts/_audit_wave_2.py --quiet   # suppress per-tool progress

Exit codes:
    0 — all wave-2 tools at score >= 8
    1 — at least one wave-2 tool is below the bar
    2 — repo layout / script missing
    3 — I/O failure
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from datetime import date

try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except (AttributeError, OSError):
    pass

SCHEMA_FILENAME = "tools.schema.json"
AUDIT_FILENAME = "docs/quality-audit.md"
RUBRIC_LINT = "scripts/rubric-lint.py"

# Wave-2 selection (matches _promote_wave_2.py's roster + _print_css_bootstrap.py).
# Sorted by JS bytes desc.
WAVE_2_SLUGS = (
    "bd-tax-calculator",
    "animal-race",
    "space-calculator",
    "age-calculator",
    "random-tools",
    "world-clock",
    "grade-calculator",
    "decision-wheel",
    "gpa-calculator",
    "loan-calculator",
    "countdown-to-date",
    "markdown-previewer",
    "calorie-estimator",
    "stopwatch",
    "compound-interest",
)


def find_repo_root(start: Path) -> Path:
    cur = start.resolve()
    for candidate in [cur, *cur.parents]:
        if (candidate / SCHEMA_FILENAME).is_file():
            return candidate
    sys.stderr.write(
        f"_audit_wave_2: cannot locate {SCHEMA_FILENAME} in {cur} or any ancestor.\n"
    )
    sys.exit(2)


def run_rubric_lint(repo_root: Path, slug: str) -> tuple[int, str, str]:
    """Run rubric-lint.py for a single slug. Returns (exit_code, stdout, stderr)."""
    proc = subprocess.run(
        [sys.executable, str(repo_root / RUBRIC_LINT), slug],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return proc.returncode, proc.stdout, proc.stderr


def parse_rubric_score(stdout: str) -> int | None:
    """Extract the integer score from rubric-lint.py's stdout (looks for 'Total: N/10'
    or 'score: N' patterns)."""
    m = re.search(r"\*\*Total:\s*(\d+)/10", stdout)
    if m:
        return int(m.group(1))
    m = re.search(r"\bscore\s*[:=]\s*(\d+)\b", stdout, re.IGNORECASE)
    return int(m.group(1)) if m else None


def parse_criterion_table(stdout: str) -> list[tuple[str, str]]:
    """Extract the per-criterion PASS/FAIL/WARN/MANUAL rows from the linter output.
    The linter emits a Markdown table of the form:
        | # | Criterion | Result | Notes | Remediation |
        |---|---|---|---|---|
        | 1 | Keyboard-complete | PASS | ... |  |
    Match the result column (one of PASS/FAIL/WARN/MANUAL)."""
    rows: list[tuple[str, str]] = []
    pattern = re.compile(
        r"^\|\s*\d+\s*\|\s+([^|]+?)\s*\|\s*(PASS|FAIL|WARN|MANUAL)\s*\|",
        re.MULTILINE,
    )
    for m in pattern.finditer(stdout):
        rows.append((m.group(1).strip(), m.group(2)))
    return rows


def strip_existing_wave_2_section(existing: str) -> str:
    """If docs/quality-audit.md already has a Wave-2 section, remove it so the
    fresh section replaces it. Wave-1 (and any other earlier) sections are kept."""
    # Match from a line beginning with "## Wave-2" or "# Quality Audit — Wave-2"
    # to end-of-file (the Wave-2 section, if present, is the last block).
    marker_patterns = (
        re.compile(r"\n# Quality Audit — Wave-2[^\n]*\n.*\Z", re.DOTALL),
        re.compile(r"\n## Wave-2[^\n]*\n.*\Z", re.DOTALL),
    )
    out = existing
    for pat in marker_patterns:
        out = pat.sub("", out)
    return out


def append_wave_2_section(repo_root: Path, results: list[dict], today: str) -> None:
    out_path = repo_root / AUDIT_FILENAME
    existing = ""
    if out_path.is_file():
        existing = out_path.read_text(encoding="utf-8", errors="ignore")
    existing = strip_existing_wave_2_section(existing)
    # Ensure the existing content ends with a blank line + our separator.
    if existing and not existing.endswith("\n"):
        existing += "\n"
    if existing and not existing.endswith("\n\n"):
        existing += "\n"

    lines: list[str] = []
    lines.append("---")
    lines.append("")
    lines.append("# Quality Audit — Wave-2 Tools")
    lines.append("")
    lines.append(f"_Auto-generated by `scripts/_audit_wave_2.py` on {today}._")
    lines.append(f"_Wave-2 tools: {len(results)} (Story 2.7)._")
    lines.append("")
    lines.append("Rubric: [docs/quality-rubric.md](./quality-rubric.md). "
                 "Score = mechanical count (PASS + half-WARN), max 10. Ready gate: score ≥ 8.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| # | Tool | Score | Bar (8) | Result |")
    lines.append("|---|---|---|---|---|")
    any_fail = False
    for i, r in enumerate(results, 1):
        score = r["score"]
        bar = "PASS" if score is not None and score >= 8 else "FAIL"
        result = "✅ green" if bar == "PASS" else "❌ below bar"
        lines.append(f"| {i} | `{r['slug']}` | {score if score is not None else '?'} | ≥ 8 | {result} |")
        if bar != "PASS":
            any_fail = True
    lines.append("")
    if any_fail:
        lines.append("**One or more wave-2 tools are below the 8/10 bar.** See per-tool "
                     "details below and remediate before promotion is recorded as green.")
    else:
        lines.append("All wave-2 tools are at or above the 8/10 bar.")
    lines.append("")
    lines.append("## Per-tool Detail")
    lines.append("")
    for r in results:
        lines.append(f"### `{r['slug']}`")
        lines.append("")
        lines.append(f"- Score: **{r['score'] if r['score'] is not None else '?'}** "
                     f"(rubric exit {r['exit']})")
        if r["criteria"]:
            lines.append("")
            lines.append("| # | Criterion | Status |")
            lines.append("|---|---|---|")
            for i, (name, status) in enumerate(r["criteria"], 1):
                lines.append(f"| {i} | {name} | {status} |")
        else:
            lines.append("")
            lines.append("_No per-criterion rows captured; rubric-lint output may have changed format._")
        lines.append("")
    new_block = "\n".join(lines) + "\n"
    out_path.write_text(existing + new_block, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Story 2.7 wave-2 audit")
    parser.add_argument("--quiet", action="store_true",
                        help="Suppress per-tool progress")
    args = parser.parse_args()

    repo_root = find_repo_root(Path(__file__).parent)
    today = date.today().isoformat()

    if not (repo_root / RUBRIC_LINT).is_file():
        sys.stderr.write(f"_audit_wave_2: missing {RUBRIC_LINT}\n")
        sys.exit(2)

    print(f"_audit_wave_2: auditing {len(WAVE_2_SLUGS)} wave-2 tools")
    results: list[dict] = []
    for slug in WAVE_2_SLUGS:
        exit_code, stdout, stderr = run_rubric_lint(repo_root, slug)
        score = parse_rubric_score(stdout)
        criteria = parse_criterion_table(stdout)
        results.append({"slug": slug, "exit": exit_code, "score": score, "criteria": criteria})
        if not args.quiet:
            print(f"  ok  {slug}: exit={exit_code}, score={score}")
        if stderr:
            sys.stderr.write(stderr)

    print(f"_audit_wave_2: appending to {AUDIT_FILENAME}")
    append_wave_2_section(repo_root, results, today)

    failures = [r for r in results if r["score"] is None or r["score"] < 8]
    if failures:
        sys.stderr.write(f"_audit_wave_2: FAIL ({len(failures)} tool(s) below 8/10)\n")
        for r in failures:
            sys.stderr.write(f"  - {r['slug']}: score={r['score']}\n")
        return 1
    print(f"_audit_wave_2: {len(WAVE_2_SLUGS)} PASS, 0 FAIL")
    return 0


if __name__ == "__main__":
    sys.exit(main())