"""Surgically update tools/date-picker-lab/index.html and tools/packs/index.html
to:

  1. Replace the FOUC IIFE with the canonical IIFE from
     assets/shell/head-snippet.html (which carries URLSearchParams('embed')
     detection + crypto.randomUUID() + window.name write).
  2. Add <script src="../../assets/js/embed.js" defer></script> right after
     the shell-thin.js <script> tag (matching the embed.js splice shell-template
     performs for tool pages).

These two pages are hand-maintained and not regenerated by shell-template.py,
so they would otherwise drift from the canonical chrome contract. The a11y
check (scripts/shell-a11y-check.py) substring-matches every page's FOUC
script against head-snippet.html's, and the embed-router smoke checks every
page carries embed.js — drift here fails both gates.

Idempotent: re-running is a no-op once the IIFE + embed.js are in place.
"""
from pathlib import Path
import re

REPO = Path(__file__).resolve().parent.parent
HEAD_SNIPPET = REPO / 'assets' / 'shell' / 'head-snippet.html'
TARGETS = [
    REPO / 'tools' / 'date-picker-lab' / 'index.html',
    REPO / 'tools' / 'packs' / 'index.html',
]


def load_canonical_iife() -> str:
    text = HEAD_SNIPPET.read_text(encoding='utf-8')
    match = re.search(r'<script>(.*?)</script>', text, re.DOTALL)
    if not match:
        raise SystemExit('FOUC IIFE not found in head-snippet.html')
    return '<script>' + match.group(1).strip() + '</script>'


# The OLD IIFE form (before Story 4.1 added the embed detection): a
# single-line IIFE that reads localStorage.ht.theme + sets data-theme +
# observes first-paint. No URLSearchParams, no UUID, no window.name.
OLD_IIFE_RE = re.compile(
    r'<script>\s*\(function\(\)\{try\{var t=localStorage\.getItem\("ht\.theme"\).*?</script>',
    re.DOTALL,
)
CANONICAL_IIFE = load_canonical_iife()

# Embed.js splice: insert right after shell-thin.js, matching the
# shell-template splice pattern (root-relative for tool pages, ../../
# for the lab + tools/packs paths).
EMBED_JS_LINE = '  <script src="../../assets/js/embed.js" defer></script>'

failures = 0
for target in TARGETS:
    text = target.read_text(encoding='utf-8')

    # 1. Replace the IIFE.
    if CANONICAL_IIFE in text:
        print(f'  iife-ok  {target.relative_to(REPO)}')
    else:
        new, n = OLD_IIFE_RE.subn(CANONICAL_IIFE, text, count=1)
        if n == 0:
            print(f'  iife-FAIL {target.relative_to(REPO)} — old IIFE pattern not found')
            failures += 1
            continue
        text = new
        print(f'  iife-fix {target.relative_to(REPO)}')

    # 2. Splice in embed.js after the shell script tag. Two anchor shapes
    #    exist (shell-template wrote ../assets/... for tools/packs/index.html
    #    and ../../assets/... for tools/<slug>/index.html + the lab page).
    if 'embed.js' in text and 'defer' in text.split('embed.js')[1][:80]:
        print(f'  embed-ok {target.relative_to(REPO)}')
    else:
        # Try both anchor forms.
        for shell_anchor, embed_line in [
            ('<script src="../../assets/js/shell-thin.js" defer></script>',
             '  <script src="../../assets/js/embed.js" defer></script>'),
            ('<script src="../assets/js/shell-thin.js" defer></script>',
             '  <script src="../assets/js/embed.js" defer></script>'),
        ]:
            if shell_anchor in text:
                text = text.replace(shell_anchor, shell_anchor + '\n' + embed_line, 1)
                target.write_text(text, encoding='utf-8')
                print(f'  embed-fix {target.relative_to(REPO)} (after {shell_anchor[:40]}...)')
                break
        else:
            print(f'  embed-FAIL {target.relative_to(REPO)} — shell-thin.js anchor not found')
            failures += 1

print(f'_fix_special_pages_iife: {failures} failure(s)')
